export const changePasswordControl = {
  newPasswordField: {
    value: '',
    key: 'newPasswordField',
    label: 'New Password',
    required: true,
    requiredErrMsg: 'New Password is required',
    patternErrMsg:
      'Please enter password in given format',
    inputType: 'password',
    displayIcon: true,
    iconName: 'password-visibility-show-dark.svg',
  },
  currentPasswordField: {
    value: '',
    key: 'currentPasswordField',
    label: 'Current Password',
    required: true,
    requiredErrMsg: 'Current Password is required',
    patternErrMsg: 'Current Password is not valid',
    inputType: 'password',
    displayIcon: true,
    iconName: 'password-visibility-show-dark.svg',
  },
  confirmPasswordField: {
    value: '',
    key: 'confirmPasswordField',
    label: 'Confirm Password',
    required: true,
    requiredErrMsg: 'Confirm Password is required',
    patternErrMsg: `Confirm Password Doesn't match with new password !`,
    inputType: 'password',
    displayIcon: true,
    iconName: 'password-visibility-show-dark.svg',
  },
};
