export const AdminControl = {
  firstName: {
    value: '',
    key: 'firstName',
    label: 'First Name',
    required: true,
    requiredErrMsg: 'First Name is required',
    inputType: 'text',
    displayIcon: false,
  },
  lastName: {
    value: '',
    key: 'lastName',
    label: 'Last Name',
    required: true,
    requiredErrMsg: 'Last Name is required',
    inputType: 'text',
    displayIcon: false,
  },
  middleName: {
    value: '',
    key: 'middleName',
    label: 'Middle Name',
    required: true,
    requiredErrMsg: 'Middle Name is required',
    inputType: 'text',
    displayIcon: false,
  },
  email: {
    value: '',
    key: 'email',
    label: 'Email',
    required: true,
    requiredErrMsg: 'Email is required',
    patternErrMsg: 'Email is invalid!!',
    inputType: 'text',
    displayIcon: false,
  },
  phoneNumber: {
    value: '',
    key: 'phoneNumber',
    label: 'Phone Number',
    required: true,
    requiredErrMsg: 'Phone Number is required',
    patternErrMsg: 'Phone Number is invalid!!',
    inputType: 'text',
    displayIcon: false,
  },
  status: {
    value: '',
    key: 'status',
    label: 'Status',
    requiredErrMsg: 'Status is required!',
  },
};
