export const testBasicDetailFormModel = {
  testName: {
    value: '',
    key: 'testName',
    label: 'Test Name',
    required: true,
    requiredErrMsg: 'Test Name is required',
    inputType: 'text',
    displayIcon: false,
  },
  status: {
    value: '',
    key: 'status',
    label: 'Status',
    required: true,
    requiredErrMsg: 'Status is required',
    inputType: 'text',
    displayIcon: false,
  },
  basicPoints: {
    value: '',
    key: 'basicPoints',
    label: 'Basic Points',
    required: true,
    requiredErrMsg: 'Field is required',
    inputType: 'text',
    displayIcon: false,
  },
  negativeMarkingPercentage: {
    value: '',
    key: 'negativeMarkingPercentage',
    label: 'NegativeMarking Percentage',
    required: true,
    requiredErrMsg: 'Field is required',
    inputType: 'text',
    displayIcon: false,
    maxLength: 3,
    maxErrMsg: 'Invalid Score',
  },
  testDuration: {
    value: '',
    key: 'testDuration',
    label: 'Test duration(min.)',
    required: true,
    requiredErrMsg: 'Field is required',
    inputType: 'text',
    displayIcon: false,
  },
  date: {
    value: '',
    key: 'date',
    label: 'Date',
    required: true,
    requiredErrMsg: 'Date is required',
    inputType: 'text',
    displayIcon: true,
  },
  startTime: {
    value: '',
    key: 'startTime',
    label: 'Start time',
    required: true,
    requiredErrMsg: 'Field is required',
    inputType: 'text',
    displayIcon: true,
  },
  endTime: {
    value: '',
    key: 'endTime',
    label: 'End time',
    required: true,
    requiredErrMsg: 'Field is required',
    inputType: 'text',
    displayIcon: true,
  },
  description: {
    value: '',
    key: 'description',
    label: 'Description',
    required: true,
    requiredErrMsg: 'Description is required',
    inputType: 'text',
    displayIcon: false,
  },
  messageAtTheStartOfTest: {
    value: '',
    key: 'messageAtTheStartOfTest',
    label: 'Message at the start of the test',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  messageAtTheEndOfTest: {
    value: '',
    key: 'messageAtTheEndOfTest',
    label: 'Message at the end of the test',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  randomQuestions: {
    value: false,
    key: 'randomQuestions',
    label: 'Random Questions',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  randomAnswers: {
    value: false,
    key: 'randomAnswers',
    label: 'Random Answers',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  logoutWhenTimeExpires: {
    value: false,
    key: 'logoutWhenTimeExpires',
    label: 'Logout when time expire',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  questignsMenu: {
    value: false,
    key: 'questignsMenu',
    label: 'Questigns menu',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
};

export const testGroupFormModel = {
  groupId: {
    value: '',
    key: 'groupId',
    label: 'Test Group',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
};
export const testGroupFilterModel = {
  search: {
    value: '',
    key: 'searchQuery',
    label: 'Search candidates..',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  collegeId: {
    value: '',
    key: 'collegeId',
    label: 'College',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
};

export const testFilterModel = {
  searchQuery: {
    value: '',
    key: 'searchQuery',
    label: 'Search candidates',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  groupId: {
    value: '',
    key: 'groupId',
    label: 'Group',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  status: {
    value: '',
    key: 'status',
    label: 'Status',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
  date: {
    value: '',
    key: 'date',
    label: 'Date',
    required: false,
    inputType: 'text',
    displayIcon: false,
  },
};
